### ISSUE TITLE
Soda vs Pop prior probability table incorrect

### ISSUE THREAD

**Issue by ZachariahRosenberg** [bayes-rules/bayes-rules.github.io#1]
In section 2.2 "Example: Pop vs soda vs coke"

https://www.bayesrulesbook.com/chapter-2.html#michelle-simple

The following table is given for the prior regional probability:
<img width="529" alt="prior_sodapop_region_tbl" src="https://user-images.githubusercontent.com/6923376/145865181-f700ba0f-ab82-433f-a8d4-d65b44239f3b.png">

However, the actual data from the repo, [pop_vs_soda]("https://github.com/bayes-rules/bayesrules/raw/master/data/pop_vs_soda.rda"), shows the following results:

<img width="366" alt="Screen Shot 2021-12-13 at 1 08 23 PM" src="https://user-images.githubusercontent.com/6923376/145865363-6bd06d29-58ef-4d4e-baad-6efe1e21da33.png">

(and here with raw value counts):
<img width="229" alt="Screen Shot 2021-12-13 at 1 08 34 PM" src="https://user-images.githubusercontent.com/6923376/145865403-614581d0-38a7-49b8-a7c9-b1c187d676fe.png">

It appears the values are correct, but assigned to the incorrect labels (e.g. 0.38 -> M, .21 -> N, etc)

Thank you!

**Comment by ajohns24** [comment]
Thanks for reaching out! The population breakdown is obtained from the U.S. Census, not the survey data. "Though the survey participants aren’t directly representative of the regional populations (Table 2.5), we can use their responses to approximate the likelihood of people using the word pop in each region:"

**Comment by ZachariahRosenberg** [comment]
Understood that the sources are different. However, the values are exact: [0.38, 0.24, 0.21, 0.17], both in table 2.5 from book and actual values from survey data.

Do you mean that while the survey data shows 38% of respondents are in Midwest, the census data has the same 38% value for the south?
